### ISSUE TITLE
rating

### ISSUE THREAD

**Issue by AriyanGeek** [DrAliRagab/Movies-Icon-Changer#3]
the xml .nfo format has changed you should change Form1 file where wants to get rating of movie
(check new format of nfo file that tmm makes)

**Comment by DrAliRagab** [comment]
I should review this.
Once I have time i will do it.

**Comment by ArunaTelshan** [comment]
Rating star is not visible in the icon.

**Comment by DrAliRagab** [comment]
It's fixed NOW
thank you feedback :)
